### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnj-legislation#13]
- [x] Write import task to catch up production site with latest bill data
- [x] Verify "Bill Text" is using the most recent version of the bill
- [x] Setup rake task to run in cron every night for session
